### PR TITLE
zh_CN.lang

### PR DESCRIPTION
**Pull request by galeboy**
text

### CODE REVIEW

**Comment by crafteverywhere** [comment]
Anyway, thx for ur help but It seems u did cause a little mess here. 
If u have any plan to go on with this, pls pay a attention to the punctuation mark usages in the existing text. And when urs is contrasted with the natural one, we can find easily that the difference is very apparent and there are also few mistakes caused by misunderstanding. Indeed, I prefer to do literal translation than to diy our own versions.

**Comment by galeboy** [comment]
I'm really sorry, give you trouble, literal translation means feel confused, and some do not match, I just try to modify it relatively easy to understand, but because I might not be familiar with how to understand, to you as the trouble I'm sorry. If you need toimprove the place, I will go to the improvement.

**Comment by galeboy** [comment]
You can leave your contact way?

**Comment by crafteverywhere** [comment]
QQ group 218895527 is a not bad place for those love magic theme minecraft mod. We talk with each others in Chinese. Sometimes I will check here, although not very frequently.

**Pull request merged**
